scoreboard:
  title: "#B37B00&lР#BD6E00&lе#C66200&lж#D05500&lи#D94800&lм #EC2F00&lP#F62200&lV#FF1500&lP" # Заголовок скорборда
  lines: # Сам скорборд
    - " "
    - "&6&l&n◢&f Не выходите"
    - "&6&l◤&f из игры &4{seconds}&f секунд."
    - " "
    - " #FFAF00С#F7A900о#EEA300п#E69E00е#DD9800р#D59200н#CC8C00и#C48700к#BB8100и#B37B00:"
    - "{enemies}"
    - " "
    - " &6Вы: &b{player} &7(&b{ping} ⇆&7)"
    - " "
    - "   &7-✦- &eКлассик &6#0 &7-✦-"
  # Если список пустой, то никакие строки не будут удалены и вместо {enemies} будет отображено "enemiesFormat.empty".
  # В противном случае будут удалены указанные строки. (счет строк начинается с 0)
  removingLinesIfNoEnemies: []
enemiesFormat:
  one: " &6&l❚ &f{player} &7(&b{ping} ⇆&7) {health}/20 &4❤" # Отображается если у игрока только один соперник или в конце если соперников больше одного.
  next: " &6&l&n❚&f {player} &7(&b{ping} ⇆&7) {health}/20 &4❤" # Все соперники кроме последнего будут отображаться так. (если соперник только один то отображается one)
  empty: " Пусто" # Отображается если список соперников пустой и список "scoreboard.removingLinesIfNoEnemies" пуст.