scoreboard:
  title: "&x&B&3&7&B&0&0&lР&x&B&D&6&E&0&0&lе&x&C&6&6&2&0&0&lж&x&D&0&5&5&0&0&lи&x&D&9&4&8&0&0&lм &x&E&C&2&F&0&0&lP&x&F&6&2&2&0&0&lV&x&F&F&1&5&0&0&lP" # Заголовок скорборда
  lines: # Сам скорборд
    - " "
    - "&6&l&n◢&f Не выходите"
    - "&6&l◤&f из игры &4{seconds}&f секунд."
    - " "
    - " &x&F&F&A&F&0&0С&x&F&7&A&9&0&0о&x&E&E&A&3&0&0п&x&E&6&9&E&0&0е&x&D&D&9&8&0&0р&x&D&5&9&2&0&0н&x&C&C&8&C&0&0и&x&C&4&8&7&0&0к&x&B&B&8&1&0&0и&x&B&3&7&B&0&0:"
    - "{enemies}"
    - " "
    - " &6Вы: &b{player} &7(&b{ping} ⇆&7)"
    - " "
    - "   &7-✦- &eКлассик &6#1 &7-✦-"
enemiesFormat:
  one: " &6&l❚ &f{player} &7(&b{ping} ⇆&7) {health}/20 &4❤" # Отображается если у игрока только один соперник или в конце если соперников больше одного.
  next: " &6&l&n❚&f {player} &7(&b{ping} ⇆&7) {health}/20 &4❤" # Все соперники кроме последнего будут отображаться так. (если соперник только один то отображается one)
  empty: " Пусто" # Отображается если список соперников пустой.